apiVersion: apps/v1
kind: Deployment
metadata:
  name: m18-cache-state-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m18-cache-state-management
  template:
    metadata:
      labels:
        app: m18-cache-state-management
    spec:
      containers:
        - name: api
          image: m18-cache-state-management:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090

