apiVersion: apps/v1
kind: Deployment
metadata:
  name: m03-notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m03-notification-service
  template:
    metadata:
      labels:
        app: m03-notification-service
    spec:
      containers:
        - name: api
          image: m03-notification-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
