apiVersion: apps/v1
kind: Deployment
metadata:
  name: M71-integration-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: M71-integration-hub
  template:
    metadata:
      labels:
        app: M71-integration-hub
    spec:
      containers:
        - name: api
          image: M71-integration-hub:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
