apiVersion: apps/v1
kind: Deployment
metadata:
  name: m58-content-recommendation-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m58-content-recommendation-engine
  template:
    metadata:
      labels:
        app: m58-content-recommendation-engine
    spec:
      containers:
        - name: api
          image: m58-content-recommendation-engine:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
