apiVersion: apps/v1
kind: Deployment
metadata:
  name: M25-auto-clipping-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: M25-auto-clipping-ai
  template:
    metadata:
      labels:
        app: M25-auto-clipping-ai
    spec:
      containers:
        - name: api
          image: M25-auto-clipping-ai:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
