apiVersion: v1
kind: Service
metadata:
  name: m25-auto-clipping-ai
spec:
  selector:
    app: m25-auto-clipping-ai
  ports:
    - name: http
      port: 80
      targetPort: 8086
    - name: grpc
      port: 9090
      targetPort: 9090

