apiVersion: apps/v1
kind: Deployment
metadata:
  name: M17-observability-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: M17-observability-monitoring
  template:
    metadata:
      labels:
        app: M17-observability-monitoring
    spec:
      containers:
        - name: api
          image: M17-observability-monitoring:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
