apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: m96-referral-fraud-detection-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: m96-referral-fraud-detection-service
