apiVersion: apps/v1
kind: Deployment
metadata:
  name: m38-content-license-verification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m38-content-license-verification
  template:
    metadata:
      labels:
        app: m38-content-license-verification
    spec:
      containers:
        - name: api
          image: m38-content-license-verification:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090

