service:
  id: M25-Auto-Clipping-AI
  cluster: data-ai
  http_port: 8086
  grpc_port: 9090
dependencies:
  clipping_tool_owner_api_url: ${M24_CLIPPING_TOOL_OWNER_API_URL}
observability:
  otlp_endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
