apiVersion: apps/v1
kind: Deployment
metadata:
  name: M44-resolution-center
spec:
  replicas: 2
  selector:
    matchLabels:
      app: M44-resolution-center
  template:
    metadata:
      labels:
        app: M44-resolution-center
    spec:
      containers:
        - name: api
          image: M44-resolution-center:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
