apiVersion: apps/v1
kind: Deployment
metadata:
  name: m50-consent-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m50-consent-service
  template:
    metadata:
      labels:
        app: m50-consent-service
    spec:
      containers:
        - name: api
          image: m50-consent-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090

