apiVersion: apps/v1
kind: Deployment
metadata:
  name: m72-webhook-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m72-webhook-manager
  template:
    metadata:
      labels:
        app: m72-webhook-manager
    spec:
      containers:
        - name: api
          image: m72-webhook-manager:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090

