apiVersion: apps/v1
kind: Deployment
metadata:
  name: m13-escrow-ledger-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m13-escrow-ledger-service
  template:
    metadata:
      labels:
        app: m13-escrow-ledger-service
    spec:
      containers:
        - name: api
          image: m13-escrow-ledger-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
