apiVersion: apps/v1
kind: Deployment
metadata:
  name: m67-event-bus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m67-event-bus
  template:
    metadata:
      labels:
        app: m67-event-bus
    spec:
      containers:
        - name: api
          image: m67-event-bus:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
