apiVersion: apps/v1
kind: Deployment
metadata:
  name: m05-billing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m05-billing-service
  template:
    metadata:
      labels:
        app: m05-billing-service
    spec:
      containers:
        - name: api
          image: m05-billing-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
