apiVersion: apps/v1
kind: Deployment
metadata:
  name: M70-developer-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: M70-developer-portal
  template:
    metadata:
      labels:
        app: M70-developer-portal
    spec:
      containers:
        - name: api
          image: M70-developer-portal:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
