apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: m01-authentication-service
  labels:
    app.kubernetes.io/name: m01-authentication-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mesh
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: m01-authentication-service
      app.kubernetes.io/component: api

