apiVersion: v1
kind: Service
metadata:
  name: m01-authentication-service
  labels:
    app.kubernetes.io/name: m01-authentication-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: mesh
spec:
  selector:
    app.kubernetes.io/name: m01-authentication-service
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090

