apiVersion: apps/v1
kind: Deployment
metadata:
  name: m01-authentication-service-worker
  labels:
    app.kubernetes.io/name: m01-authentication-service
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: m01-authentication-service
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: m01-authentication-service
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: mesh
    spec:
      containers:
        - name: m01-authentication-service-worker
          image: m01-authentication-service:latest
          imagePullPolicy: IfNotPresent
          command: ["/out/worker"]
          envFrom:
            - configMapRef:
                name: m01-authentication-service-config
            - secretRef:
                name: m01-authentication-service-secrets
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
