apiVersion: apps/v1
kind: Deployment
metadata:
  name: m12-fraud-detection-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m12-fraud-detection-engine
  template:
    metadata:
      labels:
        app: m12-fraud-detection-engine
    spec:
      containers:
        - name: api
          image: m12-fraud-detection-engine:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
