apiVersion: apps/v1
kind: Deployment
metadata:
  name: m68-retention-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m68-retention-service
  template:
    metadata:
      labels:
        app: m68-retention-service
    spec:
      containers:
        - name: api
          image: m68-retention-service:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
